#load "NetworkPanel.jai";

#load "NetworkPanelBackground.jai";
#load "NetworkPanelCursorData.jai";
#load "NetworkPanelDelete.jai";
#load "NetworkPanelEvent.jai";
#load "NetworkPanelNodeConnectionCreateDelete.jai";
#load "NetworkPanelNodeCreateDelete.jai";
#load "NetworkPanelNodeHover.jai";
#load "NetworkPanelNodePosition.jai";
#load "NetworkPanelNodeSelection.jai";
#load "NetworkPanelNodesScene.jai";
#load "NetworkPanelRender.jai";
#load "NetworkPanelResize.jai";