
#load "pipelineController/_index.jai";

#load "Renderer.jai";
#load "RendererBackground.jai";
#load "RendererCollection.jai";
#load "RendererDelete.jai";
#load "RendererEventCommands.jai";
#load "RendererPipelines.jai";
#load "RendererReadPixel.jai";
#load "RendererRender.jai";
#load "RendererResize.jai";
#if USE_IMGUI #load "RendererUI.jai";
#load "RendererUniforms.jai";
#load "RendererViewport.jai";
