#load "Material/_index.jai";

#load "LineBasicMaterial/LineBasicMaterial.jai";

#load "MeshBackgroundBasicMaterial/MeshBackgroundBasicMaterial.jai";
#load "MeshBackgroundGridMaterial/MeshBackgroundGridMaterial.jai";
#load "MeshBasicMaterial/MeshBasicMaterial.jai";
#load "MeshBasicTextureMaterial/MeshBasicTextureMaterial.jai";
#load "MeshIdMaterial/MeshIdMaterial.jai";
#load "MeshIdU32Material/MeshIdU32Material.jai";
#load "MeshNormalMaterial/MeshNormalMaterial.jai";
#load "MeshRaymarchingMaterial/MeshRaymarchingMaterial.jai";
#load "MeshTextMaterial/MeshTextMaterial.jai";
#load "MeshUVMaterial/MeshUVMaterial.jai";
#load "PointBasicMaterial/PointBasicMaterial.jai";
